### ISSUE TITLE
File Exists Problem

### ISSUE THREAD

**Issue by ymx10086** [linwhitehat/ET-BERT#95]
(ET-BERT) ymx@5950x-3090:~/ET-BERT$ bash user.sh 
Traceback (most recent call last):
  File "/home/ymx/ET-BERT/fine-tuning/run_classifier.py", line 9, in <module>
    from uer.encoders import *
  File "/home/ymx/ET-BERT/uer/encoders/__init__.py", line 1, in <module>
    from uer.encoders.transformer_encoder import TransformerEncoder
  File "/home/ymx/ET-BERT/uer/encoders/transformer_encoder.py", line 3, in <module>
    from uer.layers.transformer import TransformerLayer
  File "/home/ymx/ET-BERT/uer/layers/transformer.py", line 3, in <module>
    from uer.layers.position_ffn import PositionwiseFeedForward, GatedFeedForward
  File "/home/ymx/ET-BERT/uer/layers/position_ffn.py", line 2, in <module>
    from uer.utils import *
  File "/home/ymx/ET-BERT/uer/utils/__init__.py", line 1, in <module>
    from uer.utils.dataset import *
  File "/home/ymx/ET-BERT/uer/utils/dataset.py", line 6, in <module>
    from uer.utils.constants import *
  File "/home/ymx/ET-BERT/uer/utils/constants.py", line 4, in <module>
    with open("models/special_tokens_map.json", mode="r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/special_tokens_map.json'

I exactly did not find the file. Hope that I can get it. Thanks.

**Comment by ymx10086** [comment]
Thanks for your excellent work.
